### ISSUE TITLE
ToDo Fall 2014

### ISSUE THREAD

**Issue by ateucher** [ateucher/rcourse_site#2]
- [x] Coffee
- [x] Cream
- [x] Sugar
- [x] Coffee pot
- [x] Sticky notes
- [x] White board markers
- [x] Network cables
- [x] TV cord
- [x] USB drive with data on it
- [x] Test AWS instances
- [x] Print notes
- [x] Set up LiveMeeting
- [x] Conference call #
